// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANLFdw6SuXh71gULP49ePD7PbY0NS_8cA',
    appId: '1:716100819509:web:f6c385c294b78968466f7c',
    messagingSenderId: '716100819509',
    projectId: 'aether-4c367',
    authDomain: 'aether-4c367.firebaseapp.com',
    storageBucket: 'aether-4c367.firebasestorage.app',
    measurementId: 'G-1RHXCM8MZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZMvftr6ziPBvzdWCdEBVjFkJ_myB6oWE',
    appId: '1:716100819509:android:983b1dae82a30b49466f7c',
    messagingSenderId: '716100819509',
    projectId: 'aether-4c367',
    storageBucket: 'aether-4c367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWDaZ2r1COxapInkmqTjlB-vgwF9ZLCws',
    appId: '1:716100819509:ios:b0c70092d34a0851466f7c',
    messagingSenderId: '716100819509',
    projectId: 'aether-4c367',
    storageBucket: 'aether-4c367.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWDaZ2r1COxapInkmqTjlB-vgwF9ZLCws',
    appId: '1:716100819509:ios:b0c70092d34a0851466f7c',
    messagingSenderId: '716100819509',
    projectId: 'aether-4c367',
    storageBucket: 'aether-4c367.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANLFdw6SuXh71gULP49ePD7PbY0NS_8cA',
    appId: '1:716100819509:web:88765aafd7b28ee3466f7c',
    messagingSenderId: '716100819509',
    projectId: 'aether-4c367',
    authDomain: 'aether-4c367.firebaseapp.com',
    storageBucket: 'aether-4c367.firebasestorage.app',
    measurementId: 'G-0DHTVCE6DF',
  );
}
